### ISSUE TITLE
People picker selection disappears

### ISSUE THREAD

**Issue by stevebeauge** [pnp/sp-dev-fx-controls-react#1265]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.9.0 + spfx 1.15 ]

#### Expected / Desired Behavior / Question

Using the PeoplePicker component should be controllable (mean getting and settings values from the state).

#### Observed Behavior
The people picker allows gettings its value from the state, and trigger changes with the new selection.
However, the text input is cleared after a very small delay, even if the state actually contains the correct value

![chrome-capture-2022-6-15](https://user-images.githubusercontent.com/184604/179247079-6b675f92-cdf4-45dd-84d1-578e0cdca792.gif)

#### Steps to Reproduce

Bootstrap a new spfx webpart project using standard yeoman generator (choose webpart and react framework)
Replace the HelloWorld component with :

````tsx
import { BaseComponentContext } from '@microsoft/sp-component-base';
import { PeoplePicker, PrincipalType } from "@pnp/spfx-controls-react/lib/PeoplePicker";
import { Label, Stack } from 'office-ui-fabric-react';
import * as React from 'react';

export interface helloWorldProps {
  context: BaseComponentContext
}

export const HelloWorld = ({ context }: helloWorldProps): JSX.Element => {

  const [selectedUserId, setSelectUserId] = React.useState<string[]>([]);

  return (
    <Stack>
      <PeoplePicker
        context={context}
        defaultSelectedUsers={selectedUserId}
        titleText="People Picker"
        personSelectionLimit={3}
        showtooltip={true}
        required={true}

        onChange={(items) => {
          setSelectUserId(items.map(item => item.id));
        }}

        principalTypes={[PrincipalType.User]}
 />

      <Label>Selected ({selectedUserId.length})</Label>
      <ul>
        {selectedUserId.map(user => (
          <li key={user}>{user}</li>
        ))}
        
      </ul>
    </Stack>
  );

}
````

In the HelloworldWebPart.tsx file, change the render method to :

````tsx
  public render(): void {
    const element: React.ReactElement<helloWorldProps> = React.createElement(
      HelloWorld,
      {
        context : this.context
      }
    );

    ReactDom.render(element, this.domElement);
  }
````

Drop the webpart on any client side page

Reproduction : https://github.com/stevebeauge/spfx-react-control-sandbox/tree/repro/issue%231265

**Comment by stevebeauge** [comment]
I also tried to import from `@pnp/spfx-controls-react/lib/controls/peoplepicker`, but the behavior is the same.

As a side note, whatever the actual implementation is, we should be able to import from the module root `import { PeoplePicker } from "@pnp/spfx-controls-react";`

**Comment by stevebeauge** [comment]
Also tested with SPFX 1.14, same behavior

**Comment by stevebeauge** [comment]
I managed to find a **ugly** workaround :

````typescript
export const HelloWorld = ({ context }: helloWorldProps): JSX.Element => {

  const [selectedUsers, setSelectUsers] = React.useState<IPeoplePickerUserItem[]>([]);

  return (
    <Stack>
      <PeoplePicker
        context={context}
        defaultSelectedUsers={selectedUsers.map(user => user.loginName.substring("i:0#.f|membership|".length))}
        titleText="People Picker"
        personSelectionLimit={3}
        showtooltip={true}
        required={true}

        onChange={(items) => 
          setSelectUsers(items as IPeoplePickerUserItem[])
        }

        principalTypes={[PrincipalType.User]}
 />

      <Label>Selected ({selectedUsers.length})</Label>
      <Stack>
        {selectedUsers.map(user => (

            <Persona key={user.id} text={user.text} secondaryText={user.secondaryText} />

        ))}
        
      </Stack>
    </Stack>
  );

}
````

I guess the troubles comes from incorrect typings.

Actually the `onChange` event return a shape of data that match `IPeoplePickerUserItem` property (from pnp react control, not OUI), but is declared as `IPersonaProps` which seems to be the internal components in the picker.

**Comment by mrrobertsson** [comment]
Hi @stevebeauge

I see that it has been some time since you started this thread and may have come up with a better solution already, but in case that you haven't or other people stumble upon this issue I can post how I solved the issue. 

So first of all, the defaultSelectedUsers prop wants a string list of emails according to the documentation 
```typescript
export interface IPeoplePickerProps {
    ...
      /**
       * Default Selected User Emails
       */
      defaultSelectedUsers?: string[];
    ...
}
```
This can be set by using the return value from the `onChange` prop, it is placed in the secondaryText property of IPersonaProps.

First you need to save the value  from onChange
```typescript
const [selectedPeoplePickerUsers, setSelectedPeoplePickerUsers] = React.useState<IPersonaProps[]>([]);

<PeoplePicker
    ...
    onChange={(items : IPersonaProps[]) => {
        setSelectedPeoplePickerUsers(items);
    }}
    ...
/>
```

Then when you setting the default users of the PeoplePicker, you can he default users of the PeoplePicker, you can simply do as following:simply do as following:
```typescript
<PeoplePicker
    ...
    defaultSelectedUsers={selectedPeoplePickerUsers.map(selectedUser => selectedUser.secondaryText)}
    ...
/>
```

Hope it helps and have a good day!

**Comment by omarelanis** [comment]
@stevebeauge happened to come across this issue you raised, it's the same problem you have in the taxonomy bug you raised, you should not be updating the default or initial values otherwise it will stop the components from working correctly, so in your first code this line:

        defaultSelectedUsers={selectedUserId}

should be a constant value that never changes, you however are updating it in the onChange method using the setState, the onChange method should only be used to store the value in a separate state item which is not linked back to the control, the people picker control will handle the selected values itself.

I.e

PnPControl state -> your component state, not the other way around

You will find this is a common theme with the PnP control so avoid trying to update any readonly properties within the controls

**Comment by stevebeauge** [comment]
> 
> I.e
> 
> PnPControl state -> your component state, not the other way around
> 
> You will find this is a common theme with the PnP control so avoid trying to update any readonly properties within the controls

Sounds quite limiting. It means the control can only be used in simple scenario :(

**Comment by joelfmrodrigues** [comment]
@stevebeauge I see your point, but unfortunately the control can not be fully controlled.
I will close this bug based on the response from  @omarelanis, but if you are willing to update the component to be fully controlled, we would be happy to review the PR 🙂
