### ISSUE TITLE
RichText: multi-level ordered lists are not saved correctly

### ISSUE THREAD

**Issue by lenard-a** [pnp/sp-dev-fx-controls-react#1356]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.11.0]

#### Expected / Desired Behavior / Question
User should be capable to save multi-level ordered lists in Rich Text field.

#### Observed Behavior
When a user starts an ordered list and uses tab to add a new list level, the content is saved with one level only.

#### Steps to Reproduce

1. Start an ordered list in the Rich Text Control.
2. Add levels by using Tab.
3. Save.
4. Check saved content.

**Comment by michaelmaillot** [comment]
Hi @lenard-a,

This is because the RichText control uses [Quill](https://quilljs.com/docs/download/) Rich Text Editor. And two-levels ordered lists are displayed with specific CSS classes.

So if you want to display them accordingly, you have to add `className="ql-editor"` in the div container, like for example:

```tsx
<div className="ql-editor" dangerouslySetInnerHTML={{__html: this.state.richTextValue}} />
```

Does this helps you?
