### ISSUE TITLE
File Picker

### ISSUE THREAD

**Issue by Ahmadaboelfath** [pnp/sp-dev-fx-controls-react#1386]
[ ] Question

#### Version

Please specify what version of the library you are using: [3.12.0]

#### Expected / Desired Behavior / Question
File Picker should show the multiple upload tab when clicked when the project is using react router

#### Observed Behavior
When clicking on upload files in the file picker the app redirect to my custom error page as I am using react router in my solution, and that is because the file picker uses also router to change between tabs so in the end the url changes to a route that my app does not know so the error page renders instead of multiple upload tab, so is there any resolution regarding this point.

**Comment by michaelmaillot** [comment]
Hi @Ahmadaboelfath,

The FilePicker is using the Fluent UI `Nav` [component](https://developer.microsoft.com/en-us/fluentui#/controls/web/nav) under the hood, which updates the URL indeed. As this behavior is by design and not supposed to be aware of its environment (such as usage of 3rd party libraries like react-router), I'm not sure it has to be handled by the FilePicker control itself. I think that you have to handle this on your side. Maybe someone in the community will have additional info, as I'm not very familiar with react-router.
