### ISSUE TITLE
FolderExplorer doesn't explore folders with ' in the name

### ISSUE THREAD

**Issue by abertoletti** [pnp/sp-dev-fx-controls-react#1491]
#### Category
[ ] Enhancement
[X] Bug
[ ] Question

#### Version

Version: [3.13.0]

#### Expected / Desired Behavior / Question
The desired behaviour is that with the control FolderExplorer the folders with the char ' should be explorable

#### Observed Behavior
If you try to explore a folder with the char ' contained in the name, it results to have no subfolders.

![image](https://user-images.githubusercontent.com/35809625/226858671-63b5524d-2414-424b-a3f7-6890e19ff799.png)

![image](https://user-images.githubusercontent.com/35809625/226858518-07cf9156-7ac5-4716-9a41-bf24d65e869a.png)

#### Steps to Reproduce
In a SharePoint document library, create a folder with the char ' in the name, then a subfolder inside that.
Try to use the FolderExplorer to select the subfolder.

Thanks!

**Comment by NishkalankBezawada** [comment]
Hello @abertoletti, This issue seems to be with FolderExplorerService.ts where it fetches the folders in the folder relative url. I have tried to solve the issue now, and it seems to be working in my local. 

Below is the screen from my workbench, 
![image](https://user-images.githubusercontent.com/47456098/229191673-16acf794-6352-453f-845e-1f95e694e0e9.png)

Below is the folder structure,
![image](https://user-images.githubusercontent.com/47456098/229191758-dc779fd8-b4a3-4ec6-b728-d70c1c8bc6d6.png)

![image](https://user-images.githubusercontent.com/47456098/229191803-38180b26-fe17-4e1e-84bb-3a050e676848.png)


I will be submitting the PR soon after final checks.

Thanks,
Nishkalank
