### ISSUE TITLE
Error: EPERM: operation not permitted when "npm i"

### ISSUE THREAD

**Issue by quantrpeter** [pnp/sp-dev-fx-controls-react#1650]
Hi, i am using Nove v14 and latest sp-dev-fx-controls-react, but got error. please help thanks

![2023-09-21_12-13](https://github.com/pnp/sp-dev-fx-controls-react/assets/50471577/ed68b66b-3c30-4e08-b029-267c10dd94f2)

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/50471577/bacbdc43-d484-4f0f-aa5c-d63fca5d28df)

**Comment by michaelmaillot** [comment]
Hi @quantrpeter,

I'm not sure this error is related to SPFx Controls.

Did you try to install another package than this one?

If so, can you test the following actions:

* Remove `node_modules` folder and run `npm i`
* If problem still exists, run `npm cache clean`

Also, I've had a look at you `package.json` file, it seems that you're trying to use v3 of the Controls within a SPFx v1.12 project. FYI, it's compatible only with SPFx v1.13 or higher, as stated [here](https://pnp.github.io/sp-dev-fx-controls-react/#library-versions).

**Comment by JakeStanger** [comment]
This problem in my experience is almost exclusively antivirus-related and a general issue with Node/NPM and not package-specific. Since running `npm i` spams network requests and creates hundreds of thousands of tiny files as fast as it can, the antivirus goes all out scanning everything, which on NTFS can create some horrid lock or race condition situations that can end up causing IO to just fail like above. 

The solution usually is to add exclusions to your development directory, the NPM cache, and the Node process.
