### ISSUE TITLE
PeoplePicker - disabled

### ISSUE THREAD

**Issue by joelfmrodrigues** [pnp/sp-dev-fx-controls-react#166]
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [   1.9.0      ]

#### Expected / Desired Behavior / Question
When setting the control to disabled, it shouldn't be possible to remove users from the control 

#### Observed Behavior
When setting the control to disabled, users are still able to click on a user and remove it from the UI

#### Steps to Reproduce
Add the control in disabled mode to a page and pre-load with users.
Click on a user to remove it from the control

**Comment by tsekityam** [comment]
It is an upstream issue and addresses in OfficeDev/office-ui-fabric-react#3372

**Comment by ckruszynsky** [comment]
Has there been any update on this item? The issue is still occurring when the peoplePicker is set to disabled a user can still click the button to remove the item.  Any suggested work arounds or is there something I am missing that is supposed to be used in conjunction with setting the control to disabled?

**Comment by AJIXuMuK** [comment]
will be addressed as soon as we update to a newer version of OUIFR (FluentUI)
