### ISSUE TITLE
PeoplePicker returns no results with webAbsoluteUrl and ensureUser

### ISSUE THREAD

**Issue by argofgra** [pnp/sp-dev-fx-controls-react#1669]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.15.0 ]

#### Expected / Desired Behavior / Question
When setting webAbsoluteUrl prop to a different site and setting ensureUser = true results are expected to be returned.

#### Observed Behavior
No results are returned.
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/8049590/c5580105-3c8c-4551-b143-28220b756b01)

If both the webAbsoluteUrl prop is pointing to a different site than the current one, and ensureUser is set to true, no results are returned in the picker. Instead, the console shows the error: **PeopleSearchService::searchTenant: error occured while fetching the users.**

A deeper error says **Cannot read properties of undefined (reading 'push')**, which I've tracked down to PeopleSearchService.ensureUser:295. The object cachedLocalUsers assumes it already contains the webAbsoluteUrl as a key but it does not.

#### Steps to Reproduce

1. Add PeoplePicker control to a component
2. Provide a _webAbsoluteUrl_ value that points at a different site than the current one
3. Set _ensureUser={true}_
4. Attempt to search for users in the people picker

**Comment by NishkalankBezawada** [comment]
Hello @argofgra 

I replicated the issue. I will be creating a PR on this soon. 

@joelfmrodrigues or @AJIXuMuK kindly assign this to me. 

Thanks,
Nishkalank Bezawada

**Comment by NishkalankBezawada** [comment]
Hello @argofgra 

I have created a PR #1693 which will resolve the issue. 

The solution is as below.

#### Solution
When checked, in the method ensureUser, the user object is pushed into `this.cachedLocalUsers`. But this is empty because the user is given `webAbsoluteUrl` to fetch the users from other site collection, for which it is erroring out as `Cannot read properties of undefined (reading push)` as shown in the below figure.

<img width="419" alt="image" src="https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/758093b2-2c23-4d77-83bd-8ea8bef9264a">

By checking if `this.cachedLocalUsers` and initializing it as empty array (as below), this is working as expected. 

<img width="571" alt="image" src="https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/4ec163e6-fef9-4f45-9393-c7314087e608">

#### Screenshot with working example

![Issue 1669](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/e54ca3b6-273c-4491-8532-1ac226ac63fd)

Thanks,
Nishkalank Bezawada

**Comment by michaelmaillot** [comment]
Hi @argofgra & @NishkalankBezawada, fix has been merged to dev branch, it should be available soon in the next beta release!

Thanks to both of you 🙂
