### ISSUE TITLE
DynamicForm - Not showing the name field

### ISSUE THREAD

**Issue by hdmal** [pnp/sp-dev-fx-controls-react#1683]
#### Category

[ ] Bug

#### Version

Please specify what version of the library you are using: 3.15.0

#### Expected / Desired Behavior / Question
We have been using DynamicForm control in one of the SharePoint add-ins. Control works fine, except it's not displaying the Name (FileLeafRef) field.  Users are expecting to modify custom fields, along with the file name.

When a user is inside a Document Library, and try to edit item properties, DynamicForm control should open the form with the "Name(FileLeafRef)" field for users to edit.

SharePoint edit properties form has this feature.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/20450634/c8bda5cc-9d45-4448-8c2f-28510f396da9)

#### Observed Behavior
In a Document Library, DynamicForm opens without the "Name" field.

Configuration:
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/20450634/15a7d8f2-8ee3-4580-ae6a-09afd006b505)

Output:
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/20450634/37864059-1047-4cfc-8f70-f740fe8af4cd)

#### Steps to Reproduce
Create an SPFx project with DynamicForm control. 
Open DynamicForm to edit a file properties.

Can you please help on this?

Thanks!

**Comment by michaelmaillot** [comment]
Hi @hdmal,

The DynamicForm, by its design, is filtering list / library fields in order to display only the ones that can be "writable", I think that the initial query which gets all the fields could be updated to get the Name one (maybe something to update [here](https://github.com/pnp/sp-dev-fx-controls-react/blob/ca288e6fe0da7eaac8aa03d2a91fdbe0ac5e1dbd/src/controls/dynamicForm/DynamicForm.tsx#L773).

Would you like to give a try on this one?

**Comment by martinlingstuyl** [comment]
Ok @michaelmaillot, I think I've got it. You can close the stale PR...
