### ISSUE TITLE
Show Form Created using Form Customizer in Side Panel instead of whole page 

### ISSUE THREAD

**Issue by Lewin8687** [pnp/sp-dev-fx-controls-react#1720]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [1.18.1]

I created a form using Form Customizer. By default when clicking on "Edit all" button, its redirecting to "_layouts/15/SPListForm.aspx" followed by configured parameters. Thus, its taking the whole page to render.

Is there any way to have the same behavior as default? -- showing as a side panel when click on "Edit all" without redirecting. When close the form, still show the details pane of the selected document.

Thanks!

**Comment by michaelmaillot** [comment]
Hi @Lewin8687,

This behavior is related to SPFx ecosystem and not PnP SPFx React Controls. For now, Form Customizer extensions are displayed in a dedicated technical page which you mentioned ("SPListForm.aspx").

This is by design and can't be overridden.

I've seen in a community call that there's something on the road to replace this technical page by the side panel like the one you're refering to. But no ETA for now if I'm not mistaken.

Does this answer your question?

**Comment by Lewin8687** [comment]
Thanks @michaelmaillot! The question has been answered, i am going to close the ticket.
