### ISSUE TITLE
Error - Upgrading to SPFx 1.19.0

### ISSUE THREAD

**Issue by akshataggrwal** [pnp/sp-dev-fx-controls-react#1846]
Issue Description
We are trying to upgrade our SPFx solutions to the latest SPFx version 1.19.0. However, while upgrading, we are facing issues with some of our existing project dependencies - **@pnp/spfx-controls-react (3.x.x)** and/or @pnp/spfx-property-controls (3.x.x). The issue is when we do gulp bundle or gulp serve, it fails with the error as shown in the below screenshot.

![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/20832945/a19d4f89-06e8-41fe-af9e-2a40f2f47d0b)

What we have tried so far
We found that there is an ongoing issue in the sp-dev-docs - https://github.com/SharePoint/sp-dev-docs/issues/9675

We tried solutions/workarounds suggested in that issue thread, and one of those worked for us. Which is using beta versions of above mentioned packages. However, we are not keen on using beta packages in our solutions

"@pnp/spfx-controls-react": "4.0.0-beta.6059083",
"@pnp/spfx-property-controls": "4.0.0-beta.6059131"

Additional Environment Details
•	Node version: 18.20.3
•	SPFx version: 1.19.0

cc - @AJIXuMuK

**Comment by AJIXuMuK** [comment]
Will take a look. Thanks for reporting!

**Comment by AJIXuMuK** [comment]
@akshataggrwal - I'm not seeing any such issues with React controls library.
what component are you exporting?

**Comment by akshataggrwal** [comment]
@AJIXuMuK Thanks for your response.

I am still getting this error, and I am using "Placeholder" control from "@pnp/spfx-controls-react". Below is my package.json file for reference.

"dependencies": {
        "@microsoft/sp-component-base": "1.19.0",
        "@microsoft/sp-core-library": "1.19.0",
        "@microsoft/sp-loader": "1.19.0",
        "@microsoft/sp-lodash-subset": "1.19.0",
        "@microsoft/sp-property-pane": "1.19.0",
        "@microsoft/sp-webpart-base": "1.19.0",
        "@microsoft/sp-adaptive-card-extension-base": "1.19.0",
        "@pnp/sp": "4.2.0",
        "@pnp/spfx-controls-react": "3.18.1",
        "@pnp/spfx-property-controls": "3.17.1",
        "@fluentui/react": "8.106.4",
        "react": "17.0.1",
        "react-dom": "17.0.1",
        "tslib": "2.3.1"
    }
  
I also tried cleaning up my node modules and reinstalling them, but still getting the error.

Thanks!

**Comment by JRRSG** [comment]
> @akshataggrwal - I'm not seeing any such issues with React controls library v 3.18.1. what component are you exporting?

I am also getting this error. I started a clean form customizer solution, installed @pnp/spfx-controls-react v3.18.1 and immediately encountered this error. Removing @pnp/spfx-controls-react gets rid of the error.

**Comment by akshataggrwal** [comment]
@AJIXuMuK the issue is happening when I am using pnpm, with npm and with latest versions of the below packages it works fine.
"@pnp/spfx-controls-react": "3.18.1",
"@pnp/spfx-property-controls": "3.17.1"

Any thoughts on why pnpm may be causing the issue ?

**Comment by JRRSG** [comment]
> @AJIXuMuK the issue is happening when I am using pnpm, with npm and with latest versions of the below packages it works fine. "@pnp/spfx-controls-react": "3.18.1", "@pnp/spfx-property-controls": "3.17.1"
> 
> Any thoughts on why pnpm may be causing the issue ?

Thanks, using pnpm was causing it. I had tried compiling just this package by itself, and still got errors. I isolated the problem to coming from the Adaptive Card control and deleting those related folders got rid of all the errors but 1. The last error came back saying this:

`{
  "message": "External \"@microsoft/microsoft-graph-client\" has an unresolved version.",
  "stack": "Error: External \"@microsoft/microsoft-graph-client\" has an unresolved version at [[ManifestPlugin._getExternalsScriptResourcesAsync]] (C://Users//---//source//repos//sp-dev-fx-controls-react//node_modules//.pnpm//@microsoft+spfx-heft-plugins@1.20.1_@types+node@20.14.10_@types+webpack@4.41.38_webpack-cli@4_75suntshj4gmifjtbemncqmx5y//node_modules//@microsoft//spfx-heft-plugins//lib//spfxManifests//webpack//ManifestPlugin.js:215:31) at async [[ManifestPlugin._generateLoaderConfigurationAsync]] (C://Users//---//source//repos//sp-dev-fx-controls-react//node_modules//.pnpm//@microsoft+spfx-heft-plugins@1.20.1_@types+node@20.14.10_@types+webpack@4.41.38_webpack-cli@4_75suntshj4gmifjtbemncqmx5y//node_modules//@microsoft//spfx-heft-plugins//lib//spfxManifests//webpack//ManifestPlugin.js:172:33) at async C://Users//---//source//repos//sp-dev-fx-controls-react//node_modules//.pnpm//@microsoft+spfx-heft-plugins@1.20.1_@types+node@20.14.10_@types+webpack@4.41.38_webpack-cli@4_75suntshj4gmifjtbemncqmx5y//node_modules//@microsoft//spfx-heft-plugins//lib//spfxManifests//webpack//ManifestPlugin.js:105:57"
}`

I took your advice and switched to npm and it compiled. I don't know enough to be able to dig any further than this, but hopefully this can help the devs isolate what might be going on and if it's actually pnpm's fault or if something isn't being referenced correctly and npm is able to just ignore it and pnpm can't.

**Comment by timdhahn** [comment]
@AJIXuMuK - Are there plans to update spfx to 1.19?

I have been using pnpm in my spfx projects for the past few years without any issues. I get the same error as @JRRSG. However I was able to resolve it by using "peerDependencies" in package.json.

It looks like the issue stems from sp-dev-fx-controls-react being on 1.18.2. For some reason pnpm is having issues and I'm thinking that is because of the webpack 5 changes in 'gulp bundle' (as this wasn't causing issues before).

Here is what I went through to fix the issue

Trying to bundle our project throws an error.
![image](https://github.com/user-attachments/assets/2db1f3e2-c85a-4733-8eab-27140597455e)

When you make a change to see the error (https://github.com/SharePoint/sp-dev-docs/issues/9675#issuecomment-2150221474):
![image](https://github.com/user-attachments/assets/bcb89949-16c8-4dfa-82bc-c6334014c201)

Now, looking back to when you do a pnpm install it gives you a list of unmet peer dependencies which is a clue to solving the issue.
![image](https://github.com/user-attachments/assets/3416b5d4-3b2e-4fe4-bbd2-d9847af1956a)

**The culprit**
If we search for that package:
pnpm ls "*sp-http-msgraph" -r --depth Infinity
 
We find 1.18.2 is being referenced by @pnp/spfx-property-controls & @pnp/spfx-controls-react
![image](https://github.com/user-attachments/assets/411ca2df-7aa0-4cea-b59b-3eea4a93b075)
![image](https://github.com/user-attachments/assets/d080a588-f88a-474a-b35f-3adbd1182177)

**Solution**
Adding "peerDependencies" and the needed version of @microsoft/sp-http-msgraph solves this issue.
![image](https://github.com/user-attachments/assets/043d0d2d-381c-4cba-aa4a-9503f654eb33)

Hopefully this helps people having this issue, but keeping the versions synchronized might alleviate extra work and trouble shooting needed.

**Comment by AJIXuMuK** [comment]
Support for SPFx 1.190 has been added in the latest beta - check it out.

**Comment by timdhahn** [comment]
Thanks @AJIXuMuK. I'm able to build successfully now with pnpm
