### ISSUE TITLE
CORS Allowed in IFrameDialog

### ISSUE THREAD

**Issue by superthumper** [pnp/sp-dev-fx-controls-react#242]
#### Category
[ ] Enhancement

[ ] Bug

[x ] Question

#### Version

Please specify what version of the library you are using: [  1.11.0       ]

#### Expected / Desired Behavior / Question
I am trying to open an IFrame that is in another domain.   Is that allowed with the IFrameDialog?   Doing this within a webpart is allowed, but it seems to be a problem withing the dialog.

#### Observed Behavior
Dialog appears.   Spinner appears.   Console Errors:

SCRIPT70: Permission denied  IFrameDialogContent.tsx (44,16),

SEC7120: [CORS] The origin 'https://localhost:4321' failed to allow a cross-origin document resource at 'ms-appx-web:///assets/errorpages/forbidframingedge.htm#https://www.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=12909+Apple+View+Lane,+Burnsville,+MN+(My+Business+Name)&amp;ie=UTF8&amp;t&amp;z=14&amp;iwloc=B&amp;output=embed'.

#### Steps to Reproduce
set up the iframe dialog like this in the [webpart].tsx

<IFrameDialog 
                url={'https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;q=12909%20Apple%20View%20Lane%2C%20Burnsville%2C%20MN+(My%20Business%20Name)&amp;ie=UTF8&amp;t=&amp;z=14&amp;iwloc=B&amp;output=embed'}
                hidden={false}
                
                width={'570px'}
                height={'315px'} />

**Comment by AJIXuMuK** [comment]
Hi @superthumper 
Could you please explain what do you mean under "allowed in webpart but not allowed in dialog"?

If I do something like that in a webpart:
```typescript
<iframe src={'https://www.google.com/maps'} style={{
                border: 0,
                width: '800px',
                height: '500px'
              }} />
```
I'll get `Refused to display 'https://www.google.com/maps' in a frame because it set 'X-Frame-Options' to 'sameorigin'.` and the web part will look like that:
<img width="1073" alt="Screen Shot 2019-05-17 at 12 18 37 PM" src="https://user-images.githubusercontent.com/17036219/57951150-24424700-789e-11e9-93cd-d39196bfa369.png">
Same behavior as with the `IFrameDialog`
