### ISSUE TITLE
Using externals section of config.json

### ISSUE THREAD

**Issue by SteveClements** [pnp/sp-dev-fx-controls-react#309]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [1.11.0]

**Question**
I'd like to be able to leverage the externals section of the config.json file when using this package.
But i can't see which file for the spfx-controls-react package to reference.
As a starter i tried just to add pnp/js in as detailed here.
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts#deploy-to-production

I've also tried this 
```
"@pnp/pnpjs": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.0.1/pnpjs.es5.umd.bundle.min.js",
      "globalName": "pnp"
    }
```

But neither work and I get an error in the part saying @pnp/js could not be loaded.

Any ideas how i can use this package and reference the files externally?

Thanks!

**Comment by michaelmaillot** [comment]
Hi @SteveClements,

Are you still looking for help about this one?

The page you're refering to has been updated since, so I'm not sure that it will guide you regarding your question.

However, there's an [article](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/basics/add-an-external-library#load-a-script-from-a-cdn) that could help you about using external libraries in an SPFx project.

Regarding your question about using SPFx Controls as an external package, here's the CDN: https://www.jsdelivr.com/package/npm/@pnp/spfx-controls-react. 

Hope that it helps.
