### ISSUE TITLE
ListItemAttachments use when creating a new list item

### ISSUE THREAD

**Issue by itzzkeshav** [pnp/sp-dev-fx-controls-react#491]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://sharepoint.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[## ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [         ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
i am using list Item attachment on new list item. But in ListItemAttachments it is using ID to fetch attachment. But on new item no attachment is available and it is throwing error. 
Please help

#### Observed Behavior
_If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section._

#### Steps to Reproduce
_If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions, questions and issues are welcome, please let us know what's on your mind.
- Remember to include sufficient details and context.
- If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @itzzkeshav,

The control by design allows to work with attachments for existing items.

So, I would recommend one of these options:
1. split "Add Item" operation and add attachments as the second step when the item has been created.
2. implement some more simple UI for adding attachments to a new item. Similarly to OOTB SharePoint UI. In that case you can even use `FilePicker` component to provide more options for getting the file.


I understand the need to have the same component both for existing and new items. But it will take fairly long to implement.
So, I don't think you'll wait for us :)

**Comment by michaelmaillot** [comment]
Hi @itzzkeshav,

Latest version (3.15.0) allows to use this control with new item context. See [example](https://pnp.github.io/sp-dev-fx-controls-react/controls/ListItemAttachments/#how-to-use-this-control-in-your-solutions) in the docs.

Is it what you've looked for?
