### ISSUE TITLE
PNP-ChartControl loads old data on hover

### ISSUE THREAD

**Issue by Haritha2674** [pnp/sp-dev-fx-controls-react#620]
Hi ,
I am using using Pnp - ChartControl to load list data in Pie chart.
on page load i am fetching all list data and showing in Pie chart.
after that on drop down change i want to reload the pie chart based on dropdown value.
data is displaying in pie chart correctly but on mouse hover its showing old data also.

1. Please suggest me how to clear the old data and append new data to pie chart.
2. If i am using two charts in a single webpart and i am using different dropdown values to render the chart separately then both charts are getting impacted instead of one chart. 

please find the attached webpart file for you reference.

[homePageDashboard.zip](
![Piechart](https://user-images.githubusercontent.com/68656825/88204017-50a6df80-cc68-11ea-98c2-343cf64a82c2.PNG)
https://github.com/pnp/sp-dev-fx-controls-react/files/4961252/homePageDashboard.zip)

**Comment by AJIXuMuK** [comment]
Hello @Haritha2674,

From what I see in your code - you're using `datapromise` property of the Chart control. But later on, you are updating local variable when something is changed in the dropdown.
I assume it's better to use `data` instead of `datapromise` in that case. You can still load data when your component is mounted (`componentDidMount`). But then just update the local data (I would do that in state, not as a private var of the module) and assign it to the Chart control. Most probably you would also need to call `update` of the Chart Control.

Some additional remarks regarding your code if you don't mind.

1. Setting the state
Instead of 
```typescript
this.setState({startDateValue : startYear});
this.setState({endDateValue : endYear});
this.setState({isPickerDisabled : true});
```
you should do a single call:
```typescript
this.setState({
  startDateValue: startYear,
  endDateValue: endYear,
  isPickerDisabled: true
});
```

2. Getting data from SharePoint
There is no need to use `jQuery.ajax` to do the requests.
It's much better to use `spHttpClient` property of web part's context, or PnPjs.

3. Use `===` and `!==` instead if `==` and `!=`.

4. I would not recommend to use "static" variables in the module as they will be shared between "instances". Most probably it leads to the second issue you've described. Create private fields of the class if the data stored in the vars logically can't be part of the `state`.

If you still have issues after updating the logic - please, provide simple project we can use to reproduce the issue.
