### ISSUE TITLE
How do I make ListItemPicker the same height as mgt PeoplePicker?

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#820]
#### Category
[ ] Enhancement

[ ] Bug

[X] Question

#### Version

Please specify what version of the library you are using: [ 2.5.0]

####  Question
How do I make ListItemPicker the same height as mgt PeoplePicker? I see in dev tools both are using "flex" 

#### Observed Behavior
Project is ListItemPicker requester is mgt PeoplePicker 
![image](https://user-images.githubusercontent.com/5054931/110257008-8384b600-7f61-11eb-88c1-7877ed099027.png)

#### Steps to Reproduce
Inside <div display: grid;
    grid-template-columns: 1fr 2fr 1fr 2fr;
I have 4 divs second has ListItemPicker 4th has mgt PeoplePicker

Thanks!

**Comment by kunj-sangani** [comment]
Hi @Ofer-Gal ,

You can use Property called as class to provide a Unique class to the ListItemPicker component

For example :- className={"TestingHeight"}

Now in the SPFx webpart you can add the below css which would help you increase the height you can even use % instead of fixed height

example :- 
.TestingHeight > div > div > div > input {
    height: 50px !important;
}

Note:- This should be a global css

Attaching image for reference

![image](https://user-images.githubusercontent.com/25693207/111020268-a6dcb480-83ea-11eb-82d8-6e6f87963560.png)

**Comment by Ofer-Gal** [comment]
Thank you. I will try this

**Comment by AJIXuMuK** [comment]
Hi @Ofer-Gal,

As @kunj-sangani mentioned, currently we provide single "entry point" to modify CSS of the component - `className` property.

Let me know if you feel necessity for more granular approach.
