### ISSUE TITLE
Using controls without SPFx (outside of SharePoint)

### ISSUE THREAD

**Issue by nbelyh** [pnp/sp-dev-fx-controls-react#869]
#### Category
[ ] Enhancement

[ ] Bug

[x] Question

#### Version

Please specify what version of the library you are using: [3.0.0]

#### Question

Maybe be a stupid question, but how hard could it be to use the SPFx controls react outside the SharePoint environment?

I mean, something like hosting on own server, with OAuth connection to SharePoint (so there is no "BaseComponentContext" aka "pageContext", no "spHttpClient", and no "fetchClient", so these needs to be replaced basically?). @fluentui is available without any prerequisites basically. How much work could it be to make this happen? What could be the best strategy here (except "forget it" 😄)

Thank you in advance!

**Comment by AJIXuMuK** [comment]
Hi @nbelyh,

It will be hard as many of the controls use `BaseComponentContext` and some other classes from SPFx.
Unfortunately, there are no interfaces in the SPFx core that we could use in our type definitions instead of classes.
Because of that it could be tricky.

Theoretically, you could create your own implementation of `BaseComponentContext` and pass it to the controls as `yourContext as any`.
Probably, it could work.

**Comment by nbelyh** [comment]
@AJIXuMuK Thank you for the quick response. Actually I may need just a few controls, like filePicker/folderPicker, peoplePicker, and richText. I'll give it a shot and see how it goes.

**Comment by nbelyh** [comment]
@AJIXuMuK One question if I may - what could be a possible replacement for the theme loader? I mean, some controls are using syntax like `border-color: "[theme: neutralTertiary, default: #a19f9d]"`. As far as I understand, this assumes that the styles are being loaded using SPFx. It seems I have found the implementation here: "@microsoft/load-themed-styles". What could be a way to use this to "load the styles manually"?
