### ISSUE TITLE
Clicking internal links in RichText component while in edit mode navigates you away from the page

### ISSUE THREAD

**Issue by mbice** [pnp/sp-dev-fx-controls-react#931]
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [3.1.0]

#### Expected / Desired Behavior / Question
If I am leveraging the RichText component and there is a link in it, then clicking the link while editing a page should not navigate the user.

#### Observed Behavior
Links inside a RichText component, when editing a page, navigate when clicked. This occurs for internal links where the SharePoint routing handles the redirection. External URLs on a different domain aren't clickable at all when editing the rich text.

#### Steps to Reproduce
1. Edit a web part that has the RichText component in it.
2. Add a link to your rich text content that points to an internal page (i.e. page on your SharePoint domain). Make sure it's not a URL pointing to the same page you are editing - it must be a different page that is also internal.
3. Click the link again. Expected behavior would be to see the link button enabled and the ability to edit the URL the link points to. What actually happens is you get redirected away to that URL from the page you are editing.

Thanks!

**Comment by AJIXuMuK** [comment]
Hi @mbice,

Could you please try to use the latest version and see if the issue is still there?
If yes - could you provide some sample to reproduce it?

I've try to repro it but unsuccessfully. Here is my sample: [https://github.com/AJIXuMuK/issues/tree/master/react-controls-931](https://github.com/AJIXuMuK/issues/tree/master/react-controls-931)

**Comment by mbice** [comment]
Hi @AJIXuMuK,

Sorry, I was on vacation and didn't have a chance to look at your sample until today. I deployed it to a fresh test tenant and I can still reproduce the issue. Here are my steps (in attached video as well):

1. Edit page and add the web part with the rich text component in it
2. Add a link that points to a URL that is _**different**_ than the current page.
3. Click the newly added link (while still in edit mode) and the routing kicks in and redirects to that URL

Thanks!

https://user-images.githubusercontent.com/985283/124521161-6cd15d00-dda3-11eb-8ca9-af49a0f5e2fb.mp4

**Comment by mbice** [comment]
Hi @AJIXuMuK - any thoughts on this one? Are you now able to reproduce it on your side?

Thanks!

**Comment by AJIXuMuK** [comment]
@mbice - weird but I still can't repro it. (And sorry for the delay).

What browser are you using? Maybe it's browser-specific thing.

**Comment by mbice** [comment]
@AJIXuMuK sorry I'm not sure how I missed your last ask. This is still an issue for us and we can reproduce it in any browser (Chrome, Edge, etc). If a link is added to the RichText component, it will navigate while in edit mode IF the link is to another page on the same tenant. If the link is external it is not activated. If I link to another pages in the same site, for example, it will navigate on click and this makes editing links very difficult.

**Comment by ishaisagi-hns** [comment]
update - I replicated the issue on both tenants now - it is all up to the link you test it with.
The issue is when the link is internal (current sharepoint link) vs external.
so if you tested using "https://www.google.com" everything is fine. but test with https://[currenttenant] (does not matter what site) - it breaks.
I recommend this ticket is opened. I will review the code to see if I can find an explanation
